:sparkles: Support resx name as PO msgid & fix publish profile for .NET 8
adams85/aspnetskeleton2 pull request #7
Opened 2024-10-15 08:06 UTC by xecrets

Hi!

This is a minor addition that adds a -n or --name switch to POTools, making it use the RESX 'Name' attribute instead of 'Value' for the PO msgid. The reason being that when using it to extract PO/POT files from a RESX file, it get's a bit unwieldly with the default of using the original text as the msgid. The RESX 'Name' tends to change much less frequently, even if the actual text is tweaked, so this makes it much easier to maintain translations when using an external translation tool or service, since a change to an existing source text will not be treated as a delete/add, but as a change.

Also, I updated the publish profile to .NET 8 since the project has been updated (great, thanks!). This also necessitated add the POTools assembly as a root assembly for trimming since otherwise the command line parser breaks...

I tried to keep the changes to a minimum, conform to the coding style etc. This did make a few of the changes less than pretty, but I did not want to change any fundamentals, or method signatures etc. Still I think it's pretty clear what's going on, and as far as I can tell it's a pure addition and should not cause any compatibility problems with the previous version.

2024-10-19 09:17 UTC, adams85 requested changes
Thanks for the improvements!

Please apply the requested changes and I'll merge this.

2024-10-19 09:17 UTC, adams85 commented on tools/POTools/Services/Extracting/LocalizableTextInfo.cs
>      public string? ContextId { get; set; }
```suggestion
    public string? PluralId { get; set; }
    public string? ContextId { get; set; }
    public string? Translation { get; set; }
```

2024-10-19 09:17 UTC, adams85 commented on tools/POTools/Commands/ExtractCommand.cs
> +                        singular.Translation = text.Str;
```suggestion
                        (IPOEntry)new POSingularEntry(key) { Translation = text.Translation ?? key.Id } :
                        new POPluralEntry(key) { key.Id, key.PluralId };
```

2024-10-19 09:17 UTC, adams85 commented on tools/POTools/Commands/ExtractCommand.cs
>              return data;
```suggestion
        if (extractor == null)
            return data;
        if (extractor is ResourceTextExtractor && UseResxName)
            extractor = new ResourceNameTextExtractor();
```

2024-10-21 15:46 UTC, xecrets commented
Changed as suggested!

2024-10-21 16:13 UTC, merged

2024-10-21 17:17 UTC, adams85 commented
FYI, I found and fixed an additional bug, plus made some improvements: https://github.com/adams85/aspnetskeleton2/commit/65626b79265c1f81e22dff13c384216cb057167b